            SDL_DestroyTexture(tex);
             SDL_DestroyTexture(te1);
              SDL_DestroyTexture(te2);
               SDL_DestroyTexture(te3);
                SDL_DestroyTexture(te4);
                 SDL_DestroyTexture(te5);
                  SDL_DestroyTexture(te6);
                   SDL_DestroyTexture(te7);
                    SDL_DestroyTexture(te8);
                     SDL_DestroyTexture(te9); 
                      SDL_DestroyTexture(te10);
                       SDL_DestroyTexture(te11);
                        SDL_DestroyTexture(te12);
                         SDL_DestroyTexture(te13);
                          SDL_DestroyTexture(te14); 
                           SDL_DestroyTexture(te15);
                            SDL_DestroyTexture(te16);
                             SDL_DestroyTexture(te17);
                              SDL_DestroyTexture(te18);
                               SDL_DestroyTexture(te19);
                                SDL_DestroyTexture(te20);
                                 SDL_DestroyTexture(te21);
                                  SDL_DestroyTexture(te22);
                                   SDL_DestroyTexture(te23);
                                    SDL_DestroyTexture(te24);
                                     SDL_DestroyTexture(te25);
                                      SDL_DestroyTexture(te26);
                                       SDL_DestroyTexture(te27);
                                      //  SDL_DestroyTexture(Tr2r);
                                        // SDL_DestroyTexture(Tr1r);
                                          //SDL_DestroyTexture(Tr1b); 
                                           
